### ISSUE TITLE
start(fromStep?: string) is not working and not even starting the tutorial

### ISSUE THREAD

**Issue by srikanth716** [mohebifar/react-native-copilot#319]
I want to start the tutorial from the particular step so, provided the step number as string to start `start("6")` but the tutorial is not started

But if trigger just start `start()` then it is starting the tutorial from the first step

**Comment by srikanth716** [comment]
start("fromStep") is working as we have to provide the name of the step as 'fromStep' to start from that step

**Comment by dahed92** [comment]
The `start("fromStep")` method didn't work for me. In my app, I have several pages, and I wanted the tutorial to start from different steps when visiting different pages for the first time. What worked for me was using the `goToNth()` method. 

For example, on the first page, the user will complete steps 1, 2, and 3. When opening the second page, instead of using `start("fromStep")`, I use `goToNth(4)`. Don't forget to pass the step number, not the step name. Hope this helps!
